name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: 1.10.0
          platform: linux
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja . -B ./build
      - name: Build
        run: cmake --build ./build --target data unicorn
      - name: Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifactErrorsFailBuild: true
          artifacts: ./build/unicorn,./build/data.txt
          draft: false
          tag: v0.1.5
          
